USE BASEDEGATO;
SELECT
CODIGO,
APODO,
TURNO,
DISPONIBLE,
BUSCANDO,
FECHA,
CASILLAS
FROM JUEGOS;
delete
FROM JUEGOS;

USE BASEDEGATO;
drop table JUEGOS;
CREATE TABLE JUEGOS
(
CODIGO VARCHAR (4),
APODO VARCHAR(100) DEFAULT 'PLAYER' ,
TURNO BIT DEFAULT 1,
DISPONIBLE BIT DEFAULT 1,
BUSCANDO BIT DEFAULT 1,
FECHA DATETIME DEFAULT SYSDATETIME() ,
CASILLAS VARCHAR(20) DEFAULT ',0,0,0,0,0,0,0,0,0',
);